version: "3.9"

services:
  backend:
    build: ./backend/Api
    ports:
      - "5000:5000"
    networks:
      - nexus_network

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    networks:
      - nexus_network

  facial:
    build: ./facial_recognition
    ports:
      - "8000:8000"
    networks:
      - nexus_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nexusevents
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nexus_network

volumes:
  db_data:

networks:
  nexus_network:
